package org.oxoho.note.dto

import jakarta.validation.constraints.NotBlank
import java.time.Instant

/**
 * Request body for creating or updating a note
 *
 * Used by POST /api/v1/notes endpoint
 *
 * How it works:
 * - id is null → Creates a brand new note
 * - id is provided → Updates the existing note with that ID
 *
 * Validation:
 * - Title cannot be blank (enforced by @NotBlank)
 * - Content can be empty string (no validation)
 * - Color is a Long number representing the color (e.g., Android color int)
 *
 * Example:
 * {
 *   "id": null,
 *   "title": "Shopping List",
 *   "content": "Milk, bread, eggs",
 *   "color": 4294951175
 * }
 */
data class NoteRequest(
    val id: String?,  // Optional: null for create, provided for update

    @field:NotBlank(message = "Title can't be blank.")
    val title: String,  // Required: Note title

    val content: String,  // Note content (can be empty)

    val color: Long  // Color as a number (e.g., ARGB color value)
)

/**
 * Response body for note operations
 *
 * Returned by:
 * - POST /api/v1/notes (after creating/updating)
 * - GET /api/v1/notes (list of these)
 *
 * Contains all note information including server-generated fields:
 * - id: Auto-generated by database
 * - createdAt: Timestamp when note was created/updated
 *
 * Example:
 * {
 *   "id": "507f1f77bcf86cd799439011",
 *   "title": "Shopping List",
 *   "content": "Milk, bread, eggs",
 *   "color": 4294951175,
 *   "createdAt": "2024-01-15T10:30:00Z"
 * }
 */
data class NoteResponse(
    val id: String,          // MongoDB ObjectId as string
    val title: String,       // Note title
    val content: String,     // Note content
    val color: Long,         // Color value
    val createdAt: Instant   // When the note was created (ISO-8601 format)
)
